version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    networks:
      - my-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
